version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: "socks"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "5050:8080"
    restart: unless-stopped

  socks:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    container_name: socks
    depends_on:
      - postgres
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
